name: Terraform Plan

on:
  pull_request:
    branches:
      - main  # Change this to your target branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7  # Change to the version you are using

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -detailed-exitcode -out=tfplan
      continue-on-error: true

    - name: Show Terraform Plan Output
      if: failure()
      run: |
        echo "Terraform plan failed with exit code $?. See the output above for details."
        exit 1

    - name: Check for Changes
      if: success() && steps.plan.outcome == 'success'
      run: echo "Terraform plan detected changes or no changes."
