name: Terraform Plan

on:
  pull_request:
    branches:
      - main  # Change this to your target branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7  # Change to the version you are using

     - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        set -o pipefail
        terraform plan -no-color -detailed-exitcode > plan.out
        PLAN_EXIT_CODE=$?
        cat plan.out
        echo "::set-output name=plan_exit_code::$PLAN_EXIT_CODE"
        exit $PLAN_EXIT_CODE

    - name: Check Terraform Plan Exit Code
      id: check_plan
      run: |
        PLAN_EXIT_CODE=${{ steps.plan.outputs.plan_exit_code }}
        echo "Plan exit code: $PLAN_EXIT_CODE"
        if [ "$PLAN_EXIT_CODE" -eq 1 ]; then
          echo "Terraform plan failed. See the output above for details."
          exit 1
        elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then
          echo "Terraform plan detected changes."
        fi
