name: Terraform Plan

on:
  pull_request:
    branches:
      - '**'  # This will match all branches

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7  # Change to the version you are using

    - name: Decode GCP Credentials
      env:
        GCP_CREDENTIALS_BASE64: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
      run: |
        echo "${GCP_CREDENTIALS_BASE64}" | base64 --decode > gcp-key.json
        cat gcp-key.json  # Optional: To verify the content, remove in production

    - name: Authenticate to GCP
      run: |
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project simplehealth360  # Replace YOUR_PROJECT_ID with your actual project ID

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
      run: |
        set -e
        echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 --decode > gcp-key.json
        terraform plan -no-color -detailed-exitcode -var="use_github_actions=true" -var="credentials_json=$(cat gcp-key.json)" > plan.out
        PLAN_EXIT_CODE=$?
        echo "Terraform plan completed with exit code $PLAN_EXIT_CODE"
        cat plan.out
        echo "::set-output name=plan_exit_code::$PLAN_EXIT_CODE"
        exit $PLAN_EXIT_CODE

    - name: Check Terraform Plan Exit Code
      id: check_plan
      run: |
        PLAN_EXIT_CODE=${{ steps.plan.outputs.plan_exit_code }}
        echo "Plan exit code: $PLAN_EXIT_CODE"
        if [ "$PLAN_EXIT_CODE" -eq 1 ]; then
          echo "Terraform plan failed. See the output above for details."
          exit 1
        elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then
          echo "Terraform plan detected changes."
        fi

    - name: Debug Step
      run: echo "This is a debug step to ensure the workflow runs."
